{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ironclaw.fullname" . }}
  labels:
    {{- include "ironclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.apiToken }}
  IRONCLAW_API_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.openrouterApiKey }}
  OPENROUTER_API_KEY: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.slackBotToken }}
  SLACK_BOT_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.discordBotToken }}
  DISCORD_BOT_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.telegramBotToken }}
  TELEGRAM_BOT_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.teamsWebhookUrl }}
  IRONCLAW_TEAMS_WEBHOOK_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.signalCliUrl }}
  IRONCLAW_SIGNAL_CLI_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.signalNumber }}
  IRONCLAW_SIGNAL_NUMBER: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.rocketchatUrl }}
  IRONCLAW_ROCKETCHAT_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.rocketchatUserId }}
  IRONCLAW_ROCKETCHAT_USER_ID: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.rocketchatAuthToken }}
  IRONCLAW_ROCKETCHAT_AUTH_TOKEN: {{ . | quote }}
  {{- end }}
  {{- with .Values.secrets.rocketchatChannel }}
  IRONCLAW_ROCKETCHAT_CHANNEL: {{ . | quote }}
  {{- end }}
  {{- range $k, $v := .Values.secrets.extraEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
