# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.530"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.530/ironclaw_0.1.530_darwin_arm64.tar.gz"
      sha256 "f977979c8097dde77c95e1d6658ff82c1388b702a85f3412bf64cbb966a2b3bf"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.530/ironclaw_0.1.530_darwin_amd64.tar.gz"
      sha256 "ac16b4f196c978ecd934fddf924d85b47ebc5c6e909d414c80695c7d1fefc34c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.530/ironclaw_0.1.530_linux_arm64.tar.gz"
      sha256 "51ec74dc58e641fac316409e75fb5278ada5e7a32a8769ad358ac8ed1dbfa500"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.530/ironclaw_0.1.530_linux_amd64.tar.gz"
      sha256 "accf2505375d47d6f2d6348034b7582e517c358dbc778018803df4bd22763357"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.530
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
