# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.526"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.526/ironclaw_0.1.526_darwin_arm64.tar.gz"
      sha256 "ccd7c7eb60602d3015fce20dfe26ff85a5ae3088fb39bf8cc8a18863f873a2e3"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.526/ironclaw_0.1.526_darwin_amd64.tar.gz"
      sha256 "f3c7e20e45795cb5520399a8e3b06d9a1a326532e269ec1d0487632b36565ac3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.526/ironclaw_0.1.526_linux_arm64.tar.gz"
      sha256 "e4b124b0f34c56ed395d20c4b57026247c52b18cbd4402e75c283997b50d534c"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.526/ironclaw_0.1.526_linux_amd64.tar.gz"
      sha256 "1543a903bd67f326c7d6754717697c648b6d6c24f9122524b4aeb2cf4daf4545"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.526
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
