# typed: false
# frozen_string_literal: true

# IronClaw — security-hardened, self-hosted AI assistant platform.
#
# This formula is GENERATED by scripts/update-homebrew-formula.sh from a published
# release's SHA256SUMS — do not hand-edit the version/url/sha256 lines. To track a
# newer release, re-run that script and commit the result.
#
# Install:  brew tap IronSecCo/ironclaw https://github.com/IronSecCo/ironclaw
#           brew install ironsecco/ironclaw/ironclaw
#
# NOTE: homebrew-core ships an UNRELATED formula also named "ironclaw", and core
# wins the bare name. Always install the fully-qualified tap formula above; a bare
# "brew install ironclaw" would fetch the core package, not this one.
class Ironclaw < Formula
  desc "Security-hardened, self-hosted AI assistant platform (secured Go port)"
  homepage "https://github.com/IronSecCo/ironclaw"
  version "0.1.529"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.529/ironclaw_0.1.529_darwin_arm64.tar.gz"
      sha256 "44f0476919c40bafdf73f3579a925c13280442d491d97d7bf92d3d0e61e3ef07"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.529/ironclaw_0.1.529_darwin_amd64.tar.gz"
      sha256 "a6a3d27484e0792bd19e79865677ec2101b493f2aff7bf2a24c81251f7acc6b5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.529/ironclaw_0.1.529_linux_arm64.tar.gz"
      sha256 "6aea4e12aa75189d2689255db057475b59c9745495c87b621aa9a205895cbb98"
    end
    on_intel do
      url "https://github.com/IronSecCo/ironclaw/releases/download/v0.1.529/ironclaw_0.1.529_linux_amd64.tar.gz"
      sha256 "f92a8c2842a81937eef87399897ea824e2c2dfe9f669c263ffbee6e34d97eb1e"
    end
  end

  def install
    bin.install "ironctl"
    bin.install "ironclaw-controlplane"
    bin.install "ironclaw-sandbox"
  end

  def caveats
    <<~EOS
      ironctl, ironclaw-controlplane, and ironclaw-sandbox are now on your PATH.

      Get started:
        ironctl version
        ironctl doctor      # preflight: model creds, toolchain, sockets

      For production the control plane usually runs as a container:
        ghcr.io/ironsecco/ironclaw-controlplane:v0.1.529
      See https://ironsecco.github.io/ironclaw/quickstart/ for the full first-run flow.
    EOS
  end

  test do
    assert_match "ironctl v#{version}", shell_output("#{bin}/ironctl version")
  end
end
